### ISSUE TITLE
Minor Uptime function suggestions

### ISSUE THREAD

**Issue by ever-nascent** [suggestionsbot/suggestions-bot-js#41]
There are unnecessary parenthesis in your equation unless this is for readability? But it doesn't look much better imo.

Before

 ```		
 const days = Math.floor(ms / (secondsInADay));
const hours = Math.floor((ms % (secondsInADay)) / (secondsInAHour));
const minutes = Math.floor(((ms % (secondsInADay)) % (secondsInAHour)) / (60 * 1000));
const seconds = Math.floor(((((ms % (secondsInADay)) % (secondsInAHour)) % (60 * 1000)) / 1000));
```

After

```
const days = Math.floor(ms / secondsInADay);
const hours = Math.floor((ms % secondsInADay) / secondsInAHour);
const minutes = Math.floor(((ms % secondsInADay) % secondsInAHour) / (60 * 1000));
const seconds = Math.floor((((ms % secondsInADay) % secondsInAHour) % (60 * 1000)) / 1000);
```

Furthermore, couldn't seconds merely be 
```
const seconds = Math.floor((ms % (1000 * 60)) / 1000);
```

Instead of 
```		
const seconds = Math.floor((((ms % secondsInADay) % secondsInAHour) % (60 * 1000)) / 1000);
```

**Comment by acollierr17** [comment]
First off, thank you for this issue! This is definitely a cleaner approach and it's a function I wanted to clean up. However, I definitely forgot to take another look. This is what open source is for!

I will make a note of this and I'll be implementing this function pretty soon as the code checks out.

**Comment by ever-nascent** [comment]
No problem, it's already quite a good function in my opinion. I merely noticed minor improvements could be made. Glad to have helped!
