### ISSUE TITLE
Bot is very, very slow and laggy

### ISSUE THREAD

**Issue by DeSavanger** [suggestionsbot/suggestions-bot-js#95]
Hi,

The bot is currently very very laggy with a response time of more than 15 seconds. Sometimes the bot doesn't respond at all... Can you please fix this?

> Pong!
> Latency: 5500ms.
> Cluster 5 - Shard 20: 645ms.

Thanks in advance!

**Comment by acollierr17** [comment]
Our Github repo is not the place to report latency issues. It's to report issues with the code. I suggest you follow up with the recent posts in the support server for more information: https://discord.gg/suggestions
